version: '3.8'
services:
  db:
    image: postgres:17-alpine
    restart: always
    environment:
      - POSTGRES_USER=streamstore
      - POSTGRES_PASSWORD=streamstore
    command: postgres -c 'max_connections=1000'
    ports:
      - '5432:5432'
