services:
  cassandra1:
    image: cassandra:latest
    container_name: cassandra1
    hostname: cassandra1
    networks:
      - cassandra-net
    ports:
      - "9042:9042"
    environment: &cassandra_config
      CASSANDRA_SEEDS: "cassandra1,cassandra2"
      CASSANDRA_CLUSTER_NAME: MyCluster
      CASSANDRA_DC: datacenter1
      CASSANDRA_RACK: rack1
      CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
      CASSANDRA_NUM_TOKENS: 128

  cassandra2:
    image: cassandra:latest
    container_name: cassandra2
    hostname: cassandra2
    networks:
      - cassandra-net
    ports:
      - "9043:9042"
    environment: *cassandra_config
    depends_on:
      cassandra1:
        condition: service_started

  cassandra3:
    image: cassandra:latest
    container_name: cassandra3
    hostname: cassandra3
    networks:
      - cassandra-net
    ports:
      - "9044:9042"
    environment: *cassandra_config
    depends_on:
      cassandra2:
        condition: service_started
networks:
  cassandra-net:
    name: cassandra-net
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"