# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: StreamStore

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src -c Release --no-restore
    - name: Test
      run: dotnet test src -c Release --no-build --verbosity detailed --logger:trx
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if:  always()
      with:
        files: |
          src/StreamStore.Tests/TestResults/*.trx
    - name: Package
      run: dotnet pack src -c Release --no-build
      if: success()
    - name: Publish
      uses: maxchistt/action-publish-nuget@v1
      if: success()
      with:
        NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
        working-directory: src
