# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: StreamStore

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/**'
  workflow_dispatch:

permissions:
  checks: write
  pull-requests: write

jobs:
  build:
    name: Build, Test, Package, and Publish
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore src
    - name: Build
      run: dotnet build src -c Release --no-restore
    - name: Test
      run: dotnet test src -c Release --no-build --verbosity detailed --logger:trx --collect:"Code Coverage" --results-directory output/test-results
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/linux@v2
      if:  always()
      with:
        files: |
          output/test-results/*.trx
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    - name: Package
      run: dotnet pack src -c Release --no-build --output output/artifacts
      if: success()
    - name: Publish
      if: success() && (github.event_name == 'push' || github.event_name == 'workflow_dispatch') && github.ref == 'refs/heads/master'
      working-directory: output/artifacts
      run: dotnet nuget push *.nupkg --source "https://api.nuget.org/v3/index.json" --api-key "${{ secrets.NUGET_APIKEY }}" --skip-duplicate
